### ISSUE TITLE
mrt hangs when connecting to Atmosphere due to socket.io error

### ISSUE THREAD

**Issue by dandv** [oortcloud/meteorite#213]
Not sure if this is related to #204. I simply ran `mrt add crypto-sha1` in a fresh meteor project, and 5+ minutes have passed without any output.

```
$ mrt add crypto-sha1 --verbose
Resolving dependency tree
Connecting to atmosphere.meteor.com:443...
```

Meteorite hangs at the `ddpclient.connect()` call in [atmosphere.js line 134](https://github.com/oortcloud/meteorite/blob/master/lib/atmosphere.js#L134). Turns out the DDP call returned an error: [`reserved fields must be empty`](https://www.google.com/search?q="reserved+fields+must+be+empty")

Has anyone else encountered this behavior?

Any changes in the Atmosphere server config perhaps?

**Comment by 0shape** [comment]
$ mrt add iron-router --verbose  
Resolving dependency tree
Connecting to atmosphere.meteor.com:443...

url -X GET "https://atmosphere.meteor.com"
curl: (6) Could not resolve host: atmosphere.meteor.com

**Comment by dburles** [comment]
@0shape wow you're still using meteorite? :) an old project? you may have to update it

**Comment by tmeasday** [comment]
Yes, meteorite is official over thanks to the end of meteor.com hosting :/

**Comment by 0shape** [comment]
Thank for replies
